package starting

import "peg-solitare/types"

var Board types.Board = types.Board{
	{
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
	},
	{
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
	},
	{
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
	},
	{
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
	},
	{
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: false},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
	},
	{
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
	},
	{
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
	},
	{
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
	},
	{
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: true, Value: true},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
		{Exists: false, Value: false},
	},
}
